[workspace]
members = [
    "src/canister_initial_backend"
]
resolver = "2"


[workspace.dependencies]
candid.workspace = true
ic-stable-structures.workspace = true
ic-cdk.workspace = true
anyhow.workspace = true
ic-wasi-polyfill.workspace = true
stable-fs = "0.12.0"
